flask-tutorial/flaskr/models.py
# coding=utf-8

from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from flaskr import db, login_manager


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(32), unique=True, nullable=False)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User ({self.id}, {self.username})>'


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    author_id = db.Column(db.Integer, db.ForeignKey(User.id))
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(64), nullable=False)
    body = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f'<Post ({self.id}, {self.title})>'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


def init_db():
    db.drop_all()
    db.create_all()

flask-tutorial/flaskr/__init__.py
# coding=utf-8

import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

from config import config

db = SQLAlchemy()
migrate = Migrate(db=db)
login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_name=None):
    app = Flask(__name__)
    config_name = config_name or os.environ.get('FLASK_ENV') or 'default'
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    migrate.init_app(app)
    login_manager.init_app(app)

    from flaskr.views import auth, blog
    app.register_blueprint(auth.bp)
    app.register_blueprint(blog.bp)

    from flaskr.commands import init_db_command, generate_fake_data
    app.cli.add_command(init_db_command)
    app.cli.add_command(generate_fake_data)

    return app

flask-tutorial/flaskr/views/auth.py
# coding=utf-8

from flask import Blueprint, request, redirect, url_for, flash, \
    render_template, current_app

from flask_login import login_user, logout_user

from flaskr.models import User, db


bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=['GET', 'POST'], endpoint='register')
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif User.query.filter_by(username=username).first():
            error = f'User {username} is already registered.'

        if not error:
            user = User(username=username, password=password)
            db.session.add(user)
            db.session.commit()
            current_app.logger.info(f'Register new user {username}.')
            return redirect(url_for('auth.login'))
        else:
            flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=['GET', 'POST'], endpoint='login')
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        user = User.query.filter_by(username=username).first()
        if user and user.verify_password(password):
            login_user(user, remember=True)
            current_app.logger.debug(f'Login user {username} success.')
            next_url = request.args.get('next')
            if next_url is None or not next_url.startswith('/'):
                next_url = url_for('blog.index')
            return redirect(next_url)
        else:
            error = 'Incorrect username or password'
            current_app.logger.debug(f'Login user {username} failed, {error}')
            flash(error)
    return render_template('auth/login.html')


@bp.route('/logout', endpoint='logout')
def logout():
    logout_user()
    return redirect(url_for('blog.index'))

flask-tutorial/flaskr/views/blog.py
# coding=utf-8

from flask import Blueprint, render_template, request, redirect, url_for, \
    flash, abort
from flask_login import login_required, current_user

from flaskr.models import Post, db


bp = Blueprint('blog', __name__)


@bp.route('/', endpoint='index')
def index():
    posts = Post.query.order_by(Post.created.desc()).all()
    return render_template('blog/index.html', posts=posts)


@bp.route('/create', methods=['GET', 'POST'], endpoint='create')
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if not error:
            post = Post(title=title, body=body, author_id=current_user.id)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        else:
            flash(error)

    return render_template('blog/create.html')


@bp.route('/<int:post_id>/update', methods=['GET', 'POST'], endpoint='update')
@login_required
def update(post_id):
    post = Post.query.get(post_id)
    if post is None:
        abort(404, f'Post id {post_id} doesn\'t exists.')
    if post.author_id != current_user.id:
        abort(403)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if not error:
            post.title = title
            post.body = body
            db.session.commit()
            return redirect(url_for('blog.index'))
        else:
            flash(error)

    return render_template('blog/update.html', post=post)


# delete button is a field of form, so here using post
@bp.route('/<int:post_id>/delete', methods=['POST'], endpoint='delete')
@login_required
def delete(post_id):
    post = Post.query.get(post_id)
    if post is None:
        abort(404, f'Post id {post_id} doesn\'t exists.')
    if post.author_id != current_user.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('blog.index'))

flask-tutorial/flaskr/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1>Flaskr</h1>
  <ul>
    {% if current_user.is_authenticated %}
      <li><span>{{ current_user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

flask-tutorial/flaskr/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

flask-tutorial/flaskr/templates/blog/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
  {% if current_user.is_authenticated %}
    <a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post.title }}</h1>
          <div class="about">by {{ post.author.username }} on {{ post.created.strftime('%Y-%m-%d') }}</div>
        </div>
        {% if current_user.id == post.author_id %}
          <a class="action" href="{{ url_for('blog.update', post_id=post.id) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post.body }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

flask-tutorial/flaskr/templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or post.title }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post.body }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('blog.delete', post_id=post.id) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}